### ISSUE TITLE
error[E0599]: no variant or associated item named `Unsupported` found for enum `ErrorKind` in the current scope

### ISSUE THREAD

**Issue by charlie39** [neovide/neovide#1034]
**Describe the bug**
Neovide build fails in Arch linux.  Here's what i get 

```
error[E0599]: no variant or associated item named `Unsupported` found for enum `ErrorKind` in the current scope
  --> /tmp/neovide-git/src/neovide-git/CARGO/registry/src/github.com-1ecc6299db9ec823/rmpv-1.0.0/src/decode/mod.rs:41:53
   |
41 |             Error::DepthLimitExceeded => ErrorKind::Unsupported,
   |                                                     ^^^^^^^^^^^ variant or associated item not found in `ErrorKind`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rmpv`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'neovide-git-0.7.0.r3.ge1d8d40-1': 
error: packages failed to build: neovide-git-0.7.0.r3.ge1d8d40-1

```

**To Reproduce**
1. try Installing neovide-git from AUR

**Desktop (please complete the following information):**
 - OS: archlinux 
 - Neovide Version neovide-git in AUR [0.7.0]
 - Neovim Version  0.5.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**

**Comment by PyGamer0** [comment]
Try building from main branch manually? (or get a build from [actions](https://github.com/neovide/neovide/actions/runs/1396712234))

**Comment by kiuKisas** [comment]
I tried to build from the main branch, I confirm this issue on arch linux, via ` rust v1.52.0-nightly`

**Comment by kiuKisas** [comment]
I updated rust to `v1.58-nightly`and it works as expected, so you probably have the same issue. @charlie39 if you're using `rustup`, use `rustup update` toupdate rust and you'll be able to compile neovide :)

**Comment by dineshKumar777** [comment]
@charlie39 You are using old version. Neovide latest version is 0.8.0
Can you try building neovide from source or download executable directly from github actions page [https://github.com/neovide/neovide/actions/runs/1446953462]

**Comment by charlie39** [comment]
Sorry for the late response, got hectic for these days, that error was actually from the rpmv crate and not from neovide per say, anyway after updating rustup i tried installing today and it is building properly.
Got just a warning on unused imoort of some ParallelCommand.
```warning: unused import: `ParallelCommand` ```
It's not ciritical just thought of mentioning here. I am closing this issue

**Comment by charlie39** [comment]
Though i am able to build the git version, the prebuild release gave me the following errors while running: I don't want to open an issue for this though, just reporting:

```
Neovide version: 0.7.0
Ignored client type property: "methods"
Ignored client type property: "attributes"
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Could not create surface', src/renderer/rendered_window.rs:40:6
stack backtrace:
   0:     0x556bb04e4050 - std::backtrace_rs::backtrace::libunwind::trace::h25e12e0d899beba0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x556bb04e4050 - std::backtrace_rs::backtrace::trace_unsynchronized::h70e61195d6ae3df6
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x556bb04e4050 - std::sys_common::backtrace::_print_fmt::hba93ab80d779695a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x556bb04e4050 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf092b5883b4b2e50
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x556bb040601c - core::fmt::write::hf68bc350a8f2f0dc
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/fmt/mod.rs:1078:17
   5:     0x556bb04e38c1 - std::io::Write::write_fmt::hf66811b1bc767436
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/io/mod.rs:1517:15
   6:     0x556bb04e3225 - std::sys_common::backtrace::_print::hd425a11bfe1f20f8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x556bb04e3225 - std::sys_common::backtrace::print::h6d678795c1e61e13
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x556bb04e3225 - std::panicking::default_hook::{{closure}}::h78a02a4a0dee5e7e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:208:50
   9:     0x556bb04e28eb - std::panicking::default_hook::h56eb7eda02f355a7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:225:9
  10:     0x556bb04e28eb - std::panicking::rust_panic_with_hook::hb27ea14285131c61
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:591:17
  11:     0x556bb0501ba8 - std::panicking::begin_panic_handler::{{closure}}::hc552fcee62aad17f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13
  12:     0x556bb0501b1c - std::sys_common::backtrace::__rust_end_short_backtrace::hb9f0aa9a78e885a0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x556bb0501acd - rust_begin_unwind
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
  14:     0x556bb0404390 - core::panicking::panic_fmt::h12ac4570ea43d06f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
  15:     0x556bb040a542 - core::option::expect_failed::h7e0f81ae38d4dc42
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1260:5
  16:     0x556bb03c5814 - core::option::Option<T>::expect::h8f452010a24480b0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:349:21
  17:     0x556bb03c5814 - neovide::renderer::rendered_window::build_window_surface::ha4ce31d2e2dc0463
                               at /home/runner/work/neovide/neovide/src/renderer/rendered_window.rs:31:5
  18:     0x556bb03c5814 - neovide::renderer::rendered_window::build_window_surface_with_grid_size::hbef5f02da7fb8712
                               at /home/runner/work/neovide/neovide/src/renderer/rendered_window.rs:52:5
  19:     0x556bb03c54c4 - neovide::renderer::rendered_window::RenderedWindow::new::h3a5aedda0f13f352
  20:     0x556bb03c08cb - neovide::renderer::Renderer::draw_frame::h96b064db79b97958
  21:     0x556bb03cfadd - skulpin_renderer::renderer::Renderer::draw::h0e111049e4fe16b6
  22:     0x556bb03b1234 - neovide::window::window_wrapper::Sdl2WindowWrapper::draw_frame::h45a632078e73f017
                               at /home/runner/work/neovide/neovide/src/window/sdl2/mod.rs:368:13
  23:     0x556bb03b1234 - neovide::window::window_wrapper::start_loop::h894d4f0140af088e
                               at /home/runner/work/neovide/neovide/src/window/sdl2/mod.rs:508:15
  24:     0x556bb0367288 - neovide::window::create_window::h0f8dee7f8042e695
                               at /home/runner/work/neovide/neovide/src/window/mod.rs:112:5
  25:     0x556bb0367288 - neovide::main::he540a142533223b2
                               at /home/runner/work/neovide/neovide/src/main.rs:180:5
  26:     0x556bb052dd63 - core::ops::function::FnOnce::call_once::h211140fe246648ce
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
  27:     0x556bb052dd63 - std::sys_common::backtrace::__rust_begin_short_backtrace::haa5c536756ae6800
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:125:18
  28:     0x556bb03646c5 - main
  29:     0x7faa072ddb25 - __libc_start_main
  30:     0x556bb033460e - _start
  31:                0x0 - <unknown>
```
```

**Comment by bwubb** [comment]
Hello,

I am trying to understand how to troubleshoot this error. I have the same error code, but for a different item. I am trying to update varlociraptor via cargo.

```
Compiling data-encoding v2.5.0
   Compiling varlociraptor v8.4.5
error[E0599]: no variant or associated item named `iter` found for enum `KassRaftery` in the current scope
   --> /home/bwubb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/varlociraptor-8.4.5/src/cli.rs:777:45
    |
777 |             possible_values = &KassRaftery::iter().map(|v| v.into()).collect_vec(),
    |                                             ^^^^ variant or associated item not found in `KassRaftery`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
6   + use strum::IntoEnumIterator;
    |

error[E0599]: no variant or associated item named `iter` found for enum `KassRaftery` in the current scope
   --> /home/bwubb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/varlociraptor-8.4.5/src/testcase/runner/common/version0.rs:443:80
    |
443 |                 possible_values = { use strum::IntoEnumIterator; &KassRaftery::iter().map(|v| v.into()).collect_vec() },
    |                                                                                ^^^^ variant or associated item not found in `KassRaftery`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
120 +     use strum::IntoEnumIterator;
    |

```

I believe I updated cargo using rustup. I have a working version of varlociraptor, its just out of date and Im very confused what I have done to break it. Thank you.
