### ISSUE TITLE
Neovide not Displaying properly ['tokio-runtime-worker' panicked]

### ISSUE THREAD

**Issue by ZN0N15** [neovide/neovide#1038]
**Describe the bug**
Neovide does not display properly and all I get is a black screen and the cursor. It's giving me a bunch of errors when running it through terminal.

**To Reproduce**
1. Run neovide normally

**Expected behavior**
Neovide displays properly with my nvim config fully intact and not just a black screen

**Screenshots**
![screenshot2021-11-06-21:16:17](https://user-images.githubusercontent.com/57549197/140611183-dae56361-7a0c-47fe-bbe5-a473ebed90c3.png)

![screenshot2021-11-06-21:16:26](https://user-images.githubusercontent.com/57549197/140611194-d4747cec-7122-4772-ab65-ab3ea9c38c16.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 0.7.0
 - Neovim Version 0.6.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**

```
Ignored client type property: "methods"
Ignored client type property: "attributes"
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
```

**Additional context**
I am on Arch Linux and I get the same problem when installing it through AUR (neovide-bin and neovide-git) and also tried manually installing through source.
After building I always get the error:
```
warning: unused import: `ParallelCommand`
  --> src/bridge/handler.rs:11:26
   |
11 | use super::ui_commands::{ParallelCommand, UiCommand};
   |                          ^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `neovide` (bin "neovide") generated 1 warning
    Finished release [optimized + debuginfo] target(s) in 7.75s
```

**Comment by YUX** [comment]
same warning on m1 mba

**Comment by JeWe37** [comment]
Just had the same issue, it appears to be an issue with neovim 0.6. Downgrading to 0.5.1 fixed it for me for now. I'm assuming something about neovims communication API changed that causes this breakage.

**Comment by MRGGC** [comment]
After upgrading to neovim 0.6, I am also encountering this bug. It used to be working fine on neovim 0.5.x

**Comment by dineshKumar777** [comment]
Please use latest neovide(0.8.0). Older versions of neovide not working with latest neovim.

**Comment by howdev** [comment]
there is no build 0.8.0 binaries from github?

**Comment by fredizzimo** [comment]
The 0.8.0, version is not yet released, see https://github.com/neovide/neovide/issues/1061. It will most likely be released next week, but if you don't want to wait, you can build it from the source using the instructions in the readme.

**Comment by Kethku** [comment]
Alternatively there are builds in the wiki

**Comment by Kethku** [comment]
Closing as I'm relatively certain that this is fixed in main. Please reopen if testing in main, the issues persist.
