### ISSUE TITLE
Failed to create renderer: VkError

### ISSUE THREAD

**Issue by Froloket64** [neovide/neovide#1051]
I've tried `neovide-bin` and `neovide` packages from **AUR** and both give the error:
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create renderer: VkError(ERROR_INITIALIZATION_FAILED)', src/window/sdl2/mod.rs:459:14
stack backtrace:
   0:     0x55ac308b0d2a - <unknown>
   1:     0x55ac307ee97c - <unknown>
   2:     0x55ac308af6a4 - <unknown>
   3:     0x55ac308afe00 - <unknown>
   4:     0x55ac308af2e1 - <unknown>
   5:     0x55ac308d03a8 - <unknown>
   6:     0x55ac308d0326 - <unknown>
   7:     0x55ac308d02e2 - <unknown>
   8:     0x55ac307137a0 - <unknown>
   9:     0x55ac30713ad2 - <unknown>
  10:     0x55ac30727203 - <unknown>
  11:     0x55ac3075435d - <unknown>
  12:     0x55ac307b26e3 - <unknown>
  13:     0x55ac30750084 - <unknown>
  14:     0x7fa467a1cb25 - __libc_start_main
  15:     0x55ac30721e0e - <unknown>
  16:                0x0 - <unknown>
```

I'm using Arch (btw) and seem to have vulkan (`vulkan-intel`) and opengl (`mesa`) drivers installed.

Installation/building threw no errors (not counting **WARNING**'s while building)

**Comment by Froloket64** [comment]
Installing through **snap** and running using
```  sh
sudo snap --shell neovide
export RUST_BACKTRACE=full   # inside snap shell
neovide  # inside snap shell
```
throws another (?) error:
```
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: MESA-LOADER: failed to retrieve device information
libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: MESA-LOADER: failed to retrieve device information

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, NoAvailablePixelFormat])', src/window/window_wrapper/mod.rs:281:10
stack backtrace:
   0:     0x560b39373cc0 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x560b39373cc0 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560b39373cc0 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560b39373cc0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x560b392b5fbc - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x560b39372294 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x560b39372ebb - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x560b39372ebb - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x560b39372ebb - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x560b39371e99 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x560b39371e99 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:     0x560b3938bea8 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  12:     0x560b3938be1c - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x560b3938bdcd - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  14:     0x560b39160900 - core::panicking::panic_fmt::h12a3a3c256485fca
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
  15:     0x560b39160c32 - core::result::unwrap_failed::h2d8d0952e3250de9
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
  16:     0x560b392628c6 - core::result::Result<T,E>::unwrap::he2c056013c62a318
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1281:23
  17:     0x560b392628c6 - neovide::window::window_wrapper::create_window::hcf20f9fb48510576
                               at /root/parts/neovide/build/src/window/window_wrapper/mod.rs:274:28
  18:     0x560b391f635d - neovide::main::h6e70023db0b1cd0a
                               at /root/parts/neovide/build/src/main.rs:171:5
  19:     0x560b392073b3 - core::ops::function::FnOnce::call_once::hf6a1d5d6f2a812dd
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
  20:     0x560b392073b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h29430f71efff7f85
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:125:18
  21:     0x560b391f0e84 - main
  22:     0x7febc81f40b3 - __libc_start_main
  23:     0x560b39173d1e - _start
  24:                0x0 - <unknown>
```

**Comment by dineshKumar777** [comment]
@Froloket64 
neovide version is not mentioned. Latest is 0.8.0. 
Can you try building from source or download executable directly from github actions [https://github.com/neovide/neovide/actions/runs/1446953462]

**_also you can try these:_**
VkError with vulkan-readon [#982-comment](https://github.com/neovide/neovide/issues/982#issuecomment-928803236)
Failed to create renderer: VkError(ERROR_INITIALIZATION_FAILED)' [#401-comment](https://github.com/neovide/neovide/issues/401#issuecomment-754298854)

**Comment by Froloket64** [comment]
@dineshKumar777 
> VkError with vulkan-radeon
I have Intel Graphics, so there's no way it's applicable here

> version is not mentioned
Sorry, forgot about it. Yes, looks like it's only neovide 0.7.0-x in AUR currently.

Let me see how the build directly from git repo goes...

**Comment by Froloket64** [comment]
One thing I'd like to ask though: Should I use `https://github.com/neovide/neovide` or `https://github.com/Kethku/neovide`?

**Comment by dineshKumar777** [comment]
> One thing I'd like to ask though: Should I use `https://github.com/neovide/neovide` or `https://github.com/Kethku/neovide`?

Use https://github.com/neovide/neovide

**Comment by ardyfeb** [comment]
@dineshKumar777 after installing `neovide-git` from aur i got this different error
```
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
neovide: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

**Comment by dineshKumar777** [comment]
> @dineshKumar777 after installing `neovide-git` from aur i got this different error
> 
> ```
> [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
> [xcb] Aborting, sorry about that.
> neovide: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
> ```

https://github.com/neovide/neovide/issues/945
Already open bug for this.

**Comment by Froloket64** [comment]
Hmmm, building from the latest commit seems to **work**!
