### ISSUE TITLE
AMD mobile workstation GPU not supported

### ISSUE THREAD

**Issue by AlexCzar** [neovide/neovide#1069]
**Describe the bug**
Won't start on AMD Mobile workstation GPU.

**To Reproduce**
1. Install from snap
2. Attempt to launch (in a terminal emulator to see the error output, with rust backtrace)
3. See error

**Expected behavior**
neovide launches

**Log**
```
; env RUST_BACKTRACE=1 neovide
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: image driver extension not found
libGL error: failed to load driver: radeon
libGL error: MESA-LOADER: failed to retrieve device information
unknown chip id 0x6820, can't guess.
libGL error: failed to create dri screen
libGL error: failed to load driver: radeon
libEGL warning: MESA-LOADER: failed to retrieve device information
libEGL warning: MESA-LOADER: failed to retrieve device information

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, OsError("Couldn't find any available vsync extension")])', src/window/window_wrapper/mod.rs:281:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1281:23
   4: neovide::window::window_wrapper::create_window
             at /root/parts/neovide/build/src/window/window_wrapper/mod.rs:274:28
   5: neovide::main
             at /root/parts/neovide/build/src/main.rs:171:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Desktop (please complete the following information):**
 - OS: OpenSUSE Tumbleweed 20211202
 - Neovide Version: 0.8.0+git 2021-10-04
 - Neovim Version: 0.6.0-1.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
```
; neovide --log
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlobError { path: ".", error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Additional context**
```
; glxinfo | rg render
direct rendering: Yes
    GLX_MESA_query_renderer, GLX_MESA_swap_control, GLX_NV_float_buffer, 
    GLX_MESA_copy_sub_buffer, GLX_MESA_query_renderer, GLX_MESA_swap_control, 
Extended renderer info (GLX_MESA_query_renderer):
OpenGL renderer string: AMD VERDE (DRM 2.50.0, 5.15.5-1-default, LLVM 13.0.0)

; sudo lspci -vnnk | rg AMD
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Venus XTX [Radeon HD 8890M / R9 M275X/M375X] [1002:6820] (rev 83) (prog-if 00 [VGA controller])
```

**Comment by Kethku** [comment]
Thats very odd. Can you try running with --srgb? This will try creating a surface with the standard color space. If that works, it can be set permanently with an environment variable.

**Comment by Kethku** [comment]
Actually nvm this setting is weird. Try setting NEOVIDE_NO_SRGB environment variable and then running.

**Comment by Kethku** [comment]
For convenience I also swapped the relevant cli arg, so if you build from main, you can test with `neovide --nosrgb`

**Comment by AlexCzar** [comment]
With the version from snap neither setting `NEOVIDE_NO_SRGB=1`, nor supplying `--srgb` option worked.
Both produce exactly the same argument.
I'll try to build from the source later (maybe tomorrow) and test that.

**Comment by Kethku** [comment]
Closing for lack of response
