### ISSUE TITLE
Black window when opens from iTerm2 or terminal

### ISSUE THREAD

**Issue by bio** [neovide/neovide#1460]
**Describe the bug**
It's not possible to open `neovide` from the iTerm2 and Terminal. After running the neovide from the terminal a new black window is shown. Nothing happens after trying to enter anything in insert mode.

**To Reproduce**
1. open iTerm2
2. type `neovide` and hit enter

**Expected behavior**
No error in the terminal.

**Screenshots**

<img width="1792" alt="Screen Shot 2022-08-06 at 4 27 52 AM" src="https://user-images.githubusercontent.com/38525/183228229-bb9e88ae-ebfd-4cf9-96a0-36678b966311.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.5
 - Neovide Version 0.8.0
 - Neovim Version 0.8.0-dev-nightly-4-ge9b58a619

```
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(1)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(1)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]', src/error_handling.rs:5:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(2)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(2)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(2)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(2)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]', src/error_handling.rs:5:5
```

**Additional context**
It works as expected if the Neovide is launched via spotlight or if you click on the Neovide app.

**Comment by MultisampledNight** [comment]
Thanks for reporting! Could you share some environmental information, like the output of `echo $PATH`, `which nvim` and relevant `.zshrc` sections? Does your shell output text in `.zshrc`?

**Comment by bio** [comment]
@MultisampledNight I tried from fish and zsh shells, testcases below.

from fish
```
echo $PATH
/Users/bio/.cargo/bin /usr/local/opt/fzf/bin /opt/nvim-macos/bin /usr/local/sbin /Users/bio/Library/Caches/fnm_multishells/65695_1659794012529/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin /Applications/VMware Fusion.app/Contents/Public

which nvim
/opt/nvim-macos/bin/nvim
```

fish config: https://github.com/bio/dotfiles/tree/master/.config/fish

from zsh
```
zsh

echo $PATH
/usr/local/opt/ruby/bin:/usr/local/opt/node@10/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/Users/bio/.cargo/bin:/usr/local/opt/fzf/bin:/opt/nvim-macos/bin:/usr/local/sbin:/Users/bio/Library/Caches/fnm_multishells/65695_1659794012529/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:/Users/bio/app:/usr/local/opt/go/libexec/bin:/Users/bio/gocode/bin:/Users/bio/.cargo/bin:/usr/local/bin

which nvim
nvim: aliased to /opt/nvim-macos/bin/nvim


cat .zshrc_local
alias nvim='/opt/nvim-macos/bin/nvim'
```

.zshrc config: https://github.com/bio/dotfiles/blob/master/zshrc


> Does your shell output text in .zshrc?

I'm not sure what you mean.

**Comment by MultisampledNight** [comment]
That was a too short question of "does your shell print anything in its startup sequence". Also I can't seem to find anything out of the ordinary in the resource files, that leaves me ended up open, sorry.

**Comment by bio** [comment]
>does your shell print anything in its startup sequence

No, I disabled all zsh configs and got the same issue.

```
zsh -d -f -i
laptop% neovide
laptop% ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(1)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(1)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]', src/error_handling.rs:5:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(2)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(2)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]', src/error_handling.rs:5:5
```
<img width="906" alt="Screen Shot 2022-08-06 at 5 15 37 PM" src="https://user-images.githubusercontent.com/38525/183252685-7b46c5fd-3873-4094-9ec9-276a45370ebf.png">

**Comment by bio** [comment]
`RUST_BACKTRACE=full neovide` output below
```
laptop% RUST_BACKTRACE=full neovide
laptop% ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(1)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(1)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]', src/error_handling.rs:5:5
stack backtrace:
   0:        0x10cd83663 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6a8908fa3ed6f9e8
   1:        0x10cd17f1c - core::fmt::write::h4be00f71c5582919
   2:        0x10cd81b8a - std::io::Write::write_fmt::h49e76926070788f1
   3:        0x10cd826af - std::panicking::default_hook::{{closure}}::h1577f0656e419c0e
   4:        0x10cd81795 - std::panicking::rust_panic_with_hook::h10bc487d002f6c42
   5:        0x10cda0eca - std::panicking::begin_panic_handler::{{closure}}::hf4cfa78c105ce648
   6:        0x10cda0e38 - std::sys_common::backtrace::__rust_end_short_backtrace::h1df96a166e4351c4
   7:        0x10cda0de0 - _rust_begin_unwind
   8:        0x10d20591f - std::panicking::begin_panic_fmt::h926788b67afe29e5
   9:        0x10ccd2be9 - neovide::error_handling::show_error::h740723126b7ebbf8
  10:        0x10cc15f10 - tokio::runtime::task::raw::poll::h10b1e5d7516d7c5f
  11:        0x10cdcb476 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a141039c90bf6d8
  12:        0x10cdd49c4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h79c94dd7ef2d4714
  13:        0x10cdb257a - std::sys::unix::thread::Thread::new::thread_start::h63f8b299c7b9d50c
  14:     0x7ff81568d4e1 - __pthread_start
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(2)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format [Integer(PosInt(2)), Ext(1, [205, 3, 232]), Integer(PosInt(0)), Integer(PosInt(2)), Integer(PosInt(0)), Integer(PosInt(0)), Integer(PosInt(1))]', src/error_handling.rs:5:5
stack backtrace:
   0:        0x10cd83663 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6a8908fa3ed6f9e8
   1:        0x10cd17f1c - core::fmt::write::h4be00f71c5582919
   2:        0x10cd81b8a - std::io::Write::write_fmt::h49e76926070788f1
   3:        0x10cd826af - std::panicking::default_hook::{{closure}}::h1577f0656e419c0e
   4:        0x10cd81795 - std::panicking::rust_panic_with_hook::h10bc487d002f6c42
   5:        0x10cda0eca - std::panicking::begin_panic_handler::{{closure}}::hf4cfa78c105ce648
   6:        0x10cda0e38 - std::sys_common::backtrace::__rust_end_short_backtrace::h1df96a166e4351c4
   7:        0x10cda0de0 - _rust_begin_unwind
   8:        0x10d20591f - std::panicking::begin_panic_fmt::h926788b67afe29e5
   9:        0x10ccd2be9 - neovide::error_handling::show_error::h740723126b7ebbf8
  10:        0x10cc15f10 - tokio::runtime::task::raw::poll::h10b1e5d7516d7c5f
  11:        0x10cdcb476 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a141039c90bf6d8
  12:        0x10cdd49c4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h79c94dd7ef2d4714
  13:        0x10cdb257a - std::sys::unix::thread::Thread::new::thread_start::h63f8b299c7b9d50c
  14:     0x7ff81568d4e1 - __pthread_start
```

**Comment by jyboudreau** [comment]
@bio I noticed you have `fnm` installed. Do you by chance use it's `use-on-cd` feature? I just tracked down a similar issue for myself. I use fish and neovide does this to determine the path of nvim: 
`fish -lc "which nvim"`

Because I have [fnm](https://github.com/Schniz/fnm) installed and configured to use-on-cd. When I run neovide from a folder with a .nvmrc or .node-version it runs `fnm use` which outputs something like:
```bash
$ fish -lc "which nvim"
Using Node v18.12.1
/opt/homebrew/bin/nvim
```

I tried to fix this using --neovim-bin or NEOVIM_BIN but unfortunately this runs into the exact same issue since neovide uses `$SHELL exists -x` (presumably instead of `test -x`?) to check for existance of the NEOVIM_BIN file... 

I then tried to work around this using an alias `alias exists=test` in my fish config.

Unfortunately I eventually found out that neovide uses fish to also launch nvim and so anything output as part of fish-config will end up conflicting with neovide.

To workaround this issue I finally ended up changing my fnm.fish configuration from:
```fish
fnm env --use-on-cd | source
```

To:
```fish
fnm env | source

# This is taken from the ouput of `fnm env --use-on-cd` and modified to not output
# anything when run in non-interactive mode
function _fnm_autoload_hook --on-variable PWD --description 'Change Node version on directory change'
    status --is-command-substitution; and return
    if test -f .node-version -o -f .nvmrc 
      if status is-interactive
        fnm use --silent-if-unchanged
      else 
        fnm use --silent-if-unchanged &> /dev/null
      end
    end
end

_fnm_autoload_hook
```

Hopefully diving in this rabbit hole is useful to someone else 😢 

@MultisampledNight I was pleasantly surprised that Neovide actually worked out of the box considering my shell config. I only noticed after all this that there is a warning in the troubleshooting section about this very thing: https://github.com/neovide/neovide/blob/main/website/docs/troubleshooting.md?plain=1#L5

Maybe would be worth changing the wording a bit because I stopped reading at "if you're using zsh" initially.

**Comment by MultisampledNight** [comment]
Sure! I agree the wording is quite daunting, I also just lost track of what my original intention was _while just reading_. I'll adjust it.

**Comment by MultisampledNight** [comment]
Done in https://github.com/neovide/neovide/commit/a9979e888d111e7a1510e887211b507dd0c8d36e.

**Comment by bio** [comment]
@jyboudreau Thanks for pointing out the fnm.

I just checked the fnm and I don't use `use-on-cd` feature.
```
cat ~/.config/fish/conf.d/fnm.fish
fnm env | source
```

I upgraded the neovide to the latest v0.10.3 and the issue is gone.
@multisn8 Thank you!
