### ISSUE TITLE
Does not start on Elementary OS with nvidia proprietary drivers

### ISSUE THREAD

**Issue by luxalpa** [neovide/neovide#1526]
**Describe the bug**
When launching `neovide` I just get this output:
```
libGL error: No matching fbConfigs or visuals found                                                                                   00:33:55
libGL error: failed to load driver: swrast
libEGL warning: DRI2: failed to authenticate
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, OsError("GL context creation failed")])', src/window/window_wrapper/mod.rs:287:10
```

**To Reproduce**
1. Install Elementary OS
2. install nvidia graphics drivers
3. Probably some other steps

**Expected behavior**
Expected it to launch and not error

**Desktop (please complete the following information):**
 - OS: elementary OS 6.1 Jólnir
 - Neovide Version 0.8.0
 - Neovim Version 0.7.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
It just results in another error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlobError { path: ".", error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
it also does not work with `sudo`:
```
mkdir: cannot create directory '/run/user/0': Permission denied
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlobError { path: ".", error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by luxalpa** [comment]
I just installed it from sources (the report above was obtained via snap) and now it's working perfectly fine. Think I'll close this.
