### ISSUE TITLE
Command mode crashes neovide on nightly

### ISSUE THREAD

**Issue by Suyashtnt** [neovide/neovide#1541]
**Describe the bug**
When entering command mode (`:`), it crashes neovim instantly

**To Reproduce**
1. install neovide (latest release) and neovim nightly
2. enter command mode
3. see crash

**Expected behavior**
There to be no crash and function normally

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: NixOS 22.11 (nightly)
 - Neovide Version  0.10.1
 - Neovim Version
 ```
dotfiles on  master [!+] via ❄️  impure (nix-shell)
❯ nvim --version
NVIM v0.8.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
```
log from `--log`
```
TRACE [neovide] Neovide version: 0.10.1
```
term output from `--nofork`
```
dotfiles on  master [!+?] via ❄️  impure (nix-shell)
❯ neovide --multigrid --nofork
ERROR [neovide::error_handling] Could not parse event from neovim: invalid u64 format -1
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid u64 format -1', src/error_handling.rs:5:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR [neovide::bridge] Error joining IO loop: 'task 17 panicked'
```

**Additional context**
I'm using cmp's command line autocompletion thing if that affects this

**Comment by gimbles** [comment]
The autocompletion thing shouldn't affect this

**Comment by MultisampledNight** [comment]
Thanks for reporting!

I'm unable to reproduce this, unfortunately, running commit `6b2f0f43b5f9d375d2be1b4eb4784716dd89ec8f` from neovim master on Arch.

The error has this interesting part:

```
ERROR [neovide::error_handling] Could not parse event from neovim: invalid u64 format -1
```

Which we had in July already with some options not being validated properly, and was fixed upstream in neovim. Though anyways, if you can reproduce this with a bare config or a minimal one, it'd greatly help to clarify the situation here.

**Comment by Suyashtnt** [comment]
Ok so uh, I updated nvim and now the issue is stranger.

It seems that I can open the cmd mode fine, but whenever I type it crashes with a similar error
```
dotfiles on  master [+⇡] via ❄️  impure (nix-shell) took 6s
❯ neovide --multigrid --nofork
ERROR [neovide::error_handling] Could not parse event from neovim: invalid u64 format -1
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid u64 format -1', src/error_handling.rs:5:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR [neovide::bridge] Error joining IO loop: 'task 17 panicked'
```

**Comment by Kethku** [comment]
This should be fixed with modern neovide and nvim. Please reopen if updated installs still show this issue
