### ISSUE TITLE
How to debug this crash?

### ISSUE THREAD

**Issue by glibg10b** [neovide/neovide#2002]
Occasionally, Neovide exits abruptly. No backtrace file is produced in `$HOME`, even though `--log` is passed. The log file in the current directory contains no details about the crash:

```
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/bin/nvim" "--embed" "-p" "notes.txt", kill_on_drop: false }
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1
INFO [neovide::bridge] Neovim process attached
DEBUG [neovide::bridge::events] Ignored style attribute: "nocombine"
DEBUG [neovide::bridge::events] Ignored style attribute: "nocombine"
DEBUG [neovide::settings::window_size] Loaded window settings: Maximized
DEBUG [neovide::bridge::events] Ignored style attribute: "nocombine"
DEBUG [neovide::bridge::events] Ignored style attribute: "nocombine"
DEBUG [neovide::renderer::fonts::caching_shaper] Original font_size: 20.22px
DEBUG [neovide::renderer::fonts::caching_shaper] Original font_width: 12.44px
DEBUG [neovide::renderer::fonts::caching_shaper] Font width: 12.44px (avg: 12.44px)
DEBUG [neovide::renderer::fonts::caching_shaper] Fudge factor: 0.96
DEBUG [neovide::renderer::fonts::caching_shaper] Fudged font size: 19.50px
DEBUG [neovide::renderer::fonts::caching_shaper] Fudged font width: 12.00px
INFO [neovide::window::window_wrapper] window created (scale_factor: 1.0833, font_dimensions: Dimensions { width: 12, height: 24 })
DEBUG [neovide::renderer::fonts::caching_shaper] Updating font: 
DEBUG [neovide::renderer::fonts::caching_shaper] Font updated to: 
DEBUG [neovide::renderer::fonts::caching_shaper] Original font_size: 20.22px
DEBUG [neovide::renderer::fonts::caching_shaper] Original font_width: 12.44px
DEBUG [neovide::renderer::fonts::caching_shaper] Font width: 12.44px (avg: 12.44px)
DEBUG [neovide::renderer::fonts::caching_shaper] Fudge factor: 0.96
DEBUG [neovide::renderer::fonts::caching_shaper] Fudged font size: 19.50px
DEBUG [neovide::renderer::fonts::caching_shaper] Fudged font width: 12.00px
DEBUG [neovide::renderer::fonts::caching_shaper] Updating linespace: 0
DEBUG [neovide::renderer::fonts::caching_shaper] Linespace updated to: 0
DEBUG [neovide::renderer::fonts::caching_shaper] Original font_size: 20.22px
DEBUG [neovide::renderer::fonts::caching_shaper] Original font_width: 12.44px
DEBUG [neovide::renderer::fonts::caching_shaper] Font width: 12.44px (avg: 12.44px)
DEBUG [neovide::renderer::fonts::caching_shaper] Fudge factor: 0.96
DEBUG [neovide::renderer::fonts::caching_shaper] Fudged font size: 19.50px
DEBUG [neovide::renderer::fonts::caching_shaper] Fudged font width: 12.00px
DEBUG [neovide::renderer::fonts::caching_shaper] scale_factor changed: 0.72
DEBUG [neovide::renderer::fonts::caching_shaper] Original font_size: 13.35px
DEBUG [neovide::renderer::fonts::caching_shaper] Original font_width: 8.21px
DEBUG [neovide::renderer::fonts::caching_shaper] Font width: 8.21px (avg: 8.21px)
DEBUG [neovide::renderer::fonts::caching_shaper] Fudge factor: 0.97
DEBUG [neovide::renderer::fonts::caching_shaper] Fudged font size: 13.00px
DEBUG [neovide::renderer::fonts::caching_shaper] Fudged font width: 8.00px
```

`dmesg` doesn't even mention it, though journalctl does:

```systemctl
Aug 30 14:24:24 hydrogen systemd[1]: Started systemd-coredump@6-28355-0.service.
Aug 30 14:24:25 hydrogen systemd-coredump[28356]: elfutils disabled, parsing ELF objects not supported
Aug 30 14:24:25 hydrogen systemd-coredump[28356]: [🡕] Process 27101 (neovide) of user 1001 dumped core.
Aug 30 14:24:25 hydrogen systemd[1]: systemd-coredump@6-28355-0.service: Deactivated successfully.
```

Is there a way to get more information about the crash?

**Comment by MultisampledNight** [comment]
Hi, thanks for reporting!

Since you use systemd, if you have gdb installed you can use `coredumpctl debug` and then `backtrace` to print the backtrace. Most likely though it won't contain much information. For more extensive details, I'd recommend building from source through `CARGO_PROFILE_RELEASE_DEBUG=true cargo build --release` and trying to reproduce it through the binary from that build, which should yield more information in the gdb backtrace once crashed.

No backtrace has been written automatically since segmentation faults cannot be catched from Rust's side.

**Comment by glibg10b** [comment]
Looks like it could be a Mesa issue:

```
#0  0x00007f5cd175cb6e in ?? () from /usr/lib64/dri/crocus_dri.so
#1  0x00007f5cd1769a28 in ?? () from /usr/lib64/dri/crocus_dri.so
#2  0x00007f5cd182ec86 in ?? () from /usr/lib64/dri/crocus_dri.so
#3  0x00007f5cd174d048 in ?? () from /usr/lib64/dri/crocus_dri.so
#4  0x00007f5cd1754435 in ?? () from /usr/lib64/dri/crocus_dri.so
#5  0x00007f5cd11d080f in ?? () from /usr/lib64/dri/crocus_dri.so
#6  0x00007f5cd11d1d61 in ?? () from /usr/lib64/dri/crocus_dri.so
#7  0x00007f5cd18700ea in ?? () from /usr/lib64/dri/crocus_dri.so
#8  0x00007f5cd11ea150 in ?? () from /usr/lib64/dri/crocus_dri.so
#9  0x00007f5cd0c54464 in ?? () from /usr/lib64/dri/crocus_dri.so
#10 0x00007f5cd0a7ae3a in ?? () from /usr/lib64/dri/crocus_dri.so
#11 0x00007f5cd24fe17b in ?? () from /usr/lib64/libGLX_mesa.so.0
#12 0x00007f5cd24de3d2 in ?? () from /usr/lib64/libGLX_mesa.so.0
#13 0x0000562e9ec0da48 in ?? ()
#14 0x0000562e9eda0b06 in ?? ()
#15 0x0000562e9eda01bb in ?? ()
#16 0x0000562e9ec2b4fd in ?? ()
#17 0x0000562e9ec642ec in ?? ()
#18 0x0000562e9ec6384c in ?? ()
#19 0x0000562e9ecb4dc0 in ?? ()
#20 0x0000562e9ec1a263 in ?? ()
#21 0x0000562e9ecb2a89 in ?? ()
#22 0x00007f5cd3f7594a in __libc_start_call_main (main=main@entry=0x562e9ecb2620, argc=argc@entry=5, argv=argv@entry=0x7ffe200ac8c8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#23 0x00007f5cd3f75a05 in __libc_start_main_impl (main=0x562e9ecb2620, argc=5, argv=0x7ffe200ac8c8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffe200ac8b8) at ../csu/libc-start.c:360
#24 0x0000562e9ebc25fe in ?? ()
```

I'll see if recompiling Mesa without custom compiler flags resolves the issue (I'm on Gentoo). If not, I'll give compiling Neovide from source a go and create a new issue from there

Thanks!
