### ISSUE TITLE
`neovide --version` resulting in ` SIGSEGV (Address boundary error)`

### ISSUE THREAD

**Issue by fredizzimo** [neovide/neovide#2740]
### Discussed in https://github.com/neovide/neovide/discussions/2739

<div type='discussions-op-text'>

<sup>Originally posted by **azzamsa** July 30, 2024</sup>
Hi, 👋

I always get `signal SIGSEGV (Address boundary error)` when running `neovide --version`.

```
🐡 ❯ neovide --version
neovide 0.13.3
fish: Job 1, 'neovide --version' terminated by signal SIGSEGV (Address boundary error)

~
🐡 ❯ bash # I change my shell from fish to bash

~
🐚 ❯ neovide --version # the error persists
neovide 0.13.3
Io error: Bad file descriptor (os error 9)
Segmentation fault (core dumped)

~
🐚 ❯ nvim --version # but other app works just fine
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

Thanks for neovide 🥞
</div>

**Comment by fredizzimo** [comment]
The issue does not mention the OS. But it appears to be some wayland specific thing.


For me it randomly works and randomly crashes. Sometimes with these alternative errors:
* > Io error: Bad file descriptor (os error 9)
Error trying to flush the wayland display: Bad file descriptor (os error 9)
[1]    517760 segmentation fault (core dumped)  neovide --version
* > Io error: Cannot allocate memory (os error 12)

The issue might not even be in Neovide, it crashes in libwayland-client. I'm on Arch Linux and the package is `wayland` with the version ` 1.23.0-1`

It could also be some winit problem.

**Comment by azzamsa** [comment]
> The issue does not mention the OS. But it appears to be some wayland specific thing.

I am using:

```bash
🦊 ❯ nsysteminfo
nvim: NVIM v0.10.0
neovide: neovide 0.13.3
wezterm: wezterm 20240203-110809-5046fc22
---
OS: Fedora Linux 40 (Workstation Edition) x86_64
DE: GNOME 46.3.1
WM: Mutter (Wayland)
```

**Comment by itaranto** [comment]
Same here, using Sway in Fedora 40.

**Comment by itaranto** [comment]
Here's the backtrace reported by gdb:

```
#0  wl_map_insert_new (map=map@entry=0x557f851d34c0, data=data@entry=0x7f7cb40040b0, flags=0) at ../src/wayland-util.c:228
#1  0x00007f7cb9708a81 in proxy_create (factory=factory@entry=0x7f7cb40043b0, interface=interface@entry=0x557f60a66048, version=version@entry=3) at ../src/wayland-client.c:492
#2  0x00007f7cb9708c05 in create_outgoing_proxy (message=0x557f60a650a0, proxy=0x7f7cb40043b0, args=0x7f7cb95fe990, interface=0x557f60a66048, version=3) at ../src/wayland-client.c:739
#3  wl_proxy_marshal_array_flags (proxy=0x7f7cb40043b0, opcode=0, interface=0x557f60a66048, version=3, flags=0, args=0x7f7cb95fe990) at ../src/wayland-client.c:904
#4  0x0000557f5ee5719f in ?? ()
#5  0x0000557f5ed5c3d2 in ?? ()
#6  0x0000557f5ed611a9 in ?? ()
#7  0x0000557f5ed69f72 in ?? ()
#8  0x0000557f5eda74eb in ?? ()
#9  0x00007f7cb9cf96d7 in start_thread (arg=<optimized out>) at pthread_create.c:447
#10 0x00007f7cb9d7d60c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by Aumnescio** [comment]
Also getting this.

```
NVIM v0.10.3
neovide 0.14.0

EndeavourOS
Hyprland (Wayland)
```

**Comment by fredizzimo** [comment]
I will close this as a duplicate, since we have the full callstack in https://github.com/neovide/neovide/issues/2868. It looks like a smithay-clipboard race condition, but think the evidence is to weak to report the bug upstream.
