### ISSUE TITLE
Error: Could not compile neovide

### ISSUE THREAD

**Issue by Marin-Kitagawa** [neovide/neovide#749]
Deleted opengl issue as its known bug. Focusing on main

# Branch : `main`
## Error
This is the error I get while I compile `neovide`
```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-Wl,--as-needed" "-L" "/home/archaic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/archaic/neovide/target/release/deps/neovide-c17a0f433c37d20b.neovide.a4zaz8l8-cgu.15.rcgu.o" "-o" "/home/archaic/neovide/target/release/deps/neovide-c17a0f433c37d20b" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/archaic/neovide/target/release/deps" "-L" "/home/archaic/neovide/target/release/build/skia-bindings-1ea7a7dc34c9a9b1/out/skia" "-L" "/home/archaic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcz7srzm/libskia_bindings-2ffad62361ff7f2c.rlib" "-Wl,--start-group" "-Wl,--end-group" "/home/archaic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-c4d9a5b072ee3191.rlib" "-Wl,-Bdynamic" "-ldl" "-ldl" "-ldl" "-lstdc++" "-lfontconfig" "-lfreetype" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: cannot find -lfontconfig
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `neovide`

To learn more, run the command again with --verbose.
```

## Verbose Error

```rust
Running `rustc --crate-name neovide --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C debuginfo=2 --cfg 'feature="default"' -C metadata=c17a0f433c37d20b -C extra-filename=-c17a0f433c37d20b --out-dir /home/archaic/neovide/target/release/deps -C incremental=/home/archaic/neovide/target/release/incremental -L dependency=/home/archaic/neovide/target/release/deps --extern async_trait=/home/archaic/neovide/target/release/deps/libasync_trait-b59a5437349d382f.so --extern cfg_if=/home/archaic/neovide/target/release/deps/libcfg_if-0bc412212756a05d.rlib --extern clap=/home/archaic/neovide/target/release/deps/libclap-6685b49828a0e6d1.rlib --extern crossfire=/home/archaic/neovide/target/release/deps/libcrossfire-07fa3cb2f82d3d66.rlib --extern derive_new=/home/archaic/neovide/target/release/deps/libderive_new-2c95e35bbe6e1d7e.so --extern dirs=/home/archaic/neovide/target/release/deps/libdirs-d3615d22949eefc7.rlib --extern euclid=/home/archaic/neovide/target/release/deps/libeuclid-2bda5a603767a87a.rlib --extern flexi_logger=/home/archaic/neovide/target/release/deps/libflexi_logger-558c1fd215b5fda8.rlib --extern futures=/home/archaic/neovide/target/release/deps/libfutures-d8d4ff72a09acd29.rlib --extern gl=/home/archaic/neovide/target/release/deps/libgl-01e811b4259bd959.rlib --extern glutin=/home/archaic/neovide/target/release/deps/libglutin-367969d57e7331d8.rlib --extern image=/home/archaic/neovide/target/release/deps/libimage-afe3d807e7a90aee.rlib --extern lazy_static=/home/archaic/neovide/target/release/deps/liblazy_static-69746b95edecdf18.rlib --extern log=/home/archaic/neovide/target/release/deps/liblog-e74e20bc96977524.rlib --extern lru=/home/archaic/neovide/target/release/deps/liblru-d2e951e36167760c.rlib --extern neovide_derive=/home/archaic/neovide/target/release/deps/libneovide_derive-cc93e59a830b089f.so --extern nvim_rs=/home/archaic/neovide/target/release/deps/libnvim_rs-295a991ea27ef969.rlib --extern parking_lot=/home/archaic/neovide/target/release/deps/libparking_lot-35f5a756f7df12bb.rlib --extern pin_project=/home/archaic/neovide/target/release/deps/libpin_project-392c8ac67d4b279c.rlib --extern rand=/home/archaic/neovide/target/release/deps/librand-45ef3c762a7acf79.rlib --extern regex=/home/archaic/neovide/target/release/deps/libregex-adaf930280ef037f.rlib --extern rmpv=/home/archaic/neovide/target/release/deps/librmpv-8e0854a1e9354e41.rlib --extern rust_embed=/home/archaic/neovide/target/release/deps/librust_embed-d86f5792804ab342.rlib --extern skia_safe=/home/archaic/neovide/target/release/deps/libskia_safe-a8de592743fd7214.rlib --extern swash=/home/archaic/neovide/target/release/deps/libswash-4061d7b8e5b40440.rlib --extern tokio=/home/archaic/neovide/target/release/deps/libtokio-e524aa6ed8f1dfb0.rlib --extern unicode_segmentation=/home/archaic/neovide/target/release/deps/libunicode_segmentation-9f650cd3beeb3b42.rlib --extern which=/home/archaic/neovide/target/release/deps/libwhich-4ebb46c644c38862.rlib --extern winit=/home/archaic/neovide/target/release/deps/libwinit-12387dfd5c53deff.rlib -L /home/archaic/neovide/target/release/build/skia-bindings-1ea7a7dc34c9a9b1/out/skia`
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-Wl,--as-needed" "-L" "/home/archaic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/archaic/neovide/target/release/deps/neovide-c17a0f433c37d20b.neovide.a4zaz8l8-cgu.15.rcgu.o" "-o" "/home/archaic/neovide/target/release/deps/neovide-c17a0f433c37d20b" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/archaic/neovide/target/release/deps" "-L" "/home/archaic/neovide/target/release/build/skia-bindings-1ea7a7dc34c9a9b1/out/skia" "-L" "/home/archaic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcX12KOL/libskia_bindings-2ffad62361ff7f2c.rlib" "-Wl,--start-group" "-Wl,--end-group" "/home/archaic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-c4d9a5b072ee3191.rlib" "-Wl,-Bdynamic" "-ldl" "-ldl" "-ldl" "-lstdc++" "-lfontconfig" "-lfreetype" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: cannot find -lfontconfig
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `neovide`

Caused by:
  process didn't exit successfully: `rustc --crate-name neovide --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C debuginfo=2 --cfg 'feature="default"' -C metadata=c17a0f433c37d20b -C extra-filename=-c17a0f433c37d20b --out-dir /home/archaic/neovide/target/release/deps -C incremental=/home/archaic/neovide/target/release/incremental -L dependency=/home/archaic/neovide/target/release/deps --extern async_trait=/home/archaic/neovide/target/release/deps/libasync_trait-b59a5437349d382f.so --extern cfg_if=/home/archaic/neovide/target/release/deps/libcfg_if-0bc412212756a05d.rlib --extern clap=/home/archaic/neovide/target/release/deps/libclap-6685b49828a0e6d1.rlib --extern crossfire=/home/archaic/neovide/target/release/deps/libcrossfire-07fa3cb2f82d3d66.rlib --extern derive_new=/home/archaic/neovide/target/release/deps/libderive_new-2c95e35bbe6e1d7e.so --extern dirs=/home/archaic/neovide/target/release/deps/libdirs-d3615d22949eefc7.rlib --extern euclid=/home/archaic/neovide/target/release/deps/libeuclid-2bda5a603767a87a.rlib --extern flexi_logger=/home/archaic/neovide/target/release/deps/libflexi_logger-558c1fd215b5fda8.rlib --extern futures=/home/archaic/neovide/target/release/deps/libfutures-d8d4ff72a09acd29.rlib --extern gl=/home/archaic/neovide/target/release/deps/libgl-01e811b4259bd959.rlib --extern glutin=/home/archaic/neovide/target/release/deps/libglutin-367969d57e7331d8.rlib --extern image=/home/archaic/neovide/target/release/deps/libimage-afe3d807e7a90aee.rlib --extern lazy_static=/home/archaic/neovide/target/release/deps/liblazy_static-69746b95edecdf18.rlib --extern log=/home/archaic/neovide/target/release/deps/liblog-e74e20bc96977524.rlib --extern lru=/home/archaic/neovide/target/release/deps/liblru-d2e951e36167760c.rlib --extern neovide_derive=/home/archaic/neovide/target/release/deps/libneovide_derive-cc93e59a830b089f.so --extern nvim_rs=/home/archaic/neovide/target/release/deps/libnvim_rs-295a991ea27ef969.rlib --extern parking_lot=/home/archaic/neovide/target/release/deps/libparking_lot-35f5a756f7df12bb.rlib --extern pin_project=/home/archaic/neovide/target/release/deps/libpin_project-392c8ac67d4b279c.rlib --extern rand=/home/archaic/neovide/target/release/deps/librand-45ef3c762a7acf79.rlib --extern regex=/home/archaic/neovide/target/release/deps/libregex-adaf930280ef037f.rlib --extern rmpv=/home/archaic/neovide/target/release/deps/librmpv-8e0854a1e9354e41.rlib --extern rust_embed=/home/archaic/neovide/target/release/deps/librust_embed-d86f5792804ab342.rlib --extern skia_safe=/home/archaic/neovide/target/release/deps/libskia_safe-a8de592743fd7214.rlib --extern swash=/home/archaic/neovide/target/release/deps/libswash-4061d7b8e5b40440.rlib --extern tokio=/home/archaic/neovide/target/release/deps/libtokio-e524aa6ed8f1dfb0.rlib --extern unicode_segmentation=/home/archaic/neovide/target/release/deps/libunicode_segmentation-9f650cd3beeb3b42.rlib --extern which=/home/archaic/neovide/target/release/deps/libwhich-4ebb46c644c38862.rlib --extern winit=/home/archaic/neovide/target/release/deps/libwinit-12387dfd5c53deff.rlib -L /home/archaic/neovide/target/release/build/skia-bindings-1ea7a7dc34c9a9b1/out/skia` (exit status: 1)
```

# Specifications

OS : Kubuntu (21.04)
Rust: 1.53.0
Kernel: 5.11.0-22-generic

This is a fresh installation.

**Comment by Kethku** [comment]
Don't use the opengl branch. It has been merged to main.

**Comment by Kethku** [comment]
Did you install the dependencies in the readme?

sudo apt install -y curl \
    gnupg ca-certificates git \
    gcc-multilib g++-multilib cmake libssl-dev pkg-config \
    libfreetype6-dev libasound2-dev libexpat1-dev libxcb-composite0-dev \
    libbz2-dev libsndio-dev freeglut3-dev libxmu-dev libxi-dev libfontconfig1-dev
    
Is it possible that your rust toolchain is installed wrong? https://github.com/alacritty/alacritty/issues/1473

**Comment by ruby-zen** [comment]
> Did you install the dependencies in the readme?
> 
> sudo apt install -y curl
> gnupg ca-certificates git
> gcc-multilib g++-multilib cmake libssl-dev pkg-config
> libfreetype6-dev libasound2-dev libexpat1-dev libxcb-composite0-dev
> libbz2-dev libsndio-dev freeglut3-dev libxmu-dev libxi-dev libfontconfig1-dev
> 
> Is it possible that your rust toolchain is installed wrong? [alacritty/alacritty#1473](https://github.com/alacritty/alacritty/issues/1473)

I already installed all the dependencies correctly. It compiled after installing `Rust` for `x86_64-unknown-linux-gnu`. But now, I get the following error
```rust
Ignored client type property: "methods"
Ignored client type property: "attributes"
libEGL warning: DRI2: failed to authenticate
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, OsError("Couldn't find any available vsync extension")])', src/window/window_wrapper/mod.rs:242:10
stack backtrace:
   0:     0x563bc4a3f770 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x563bc4a3f770 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563bc4a3f770 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x563bc4a3f770 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x563bc4816c2f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x563bc4a3ef94 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x563bc4a3ea2b - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x563bc4a3ea2b - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x563bc4a3ea2b - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x563bc4a3dd35 - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x563bc4a3dd35 - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x563bc4a597e8 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:     0x563bc4a5975c - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x563bc4a5970d - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x563bc47601e0 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x563bc47608d2 - core::result::unwrap_failed::hcbdf25d28ce8f0ca
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
  16:     0x563bc494dca1 - core::result::Result<T,E>::unwrap::h84ca4eca05d2ed55
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1037:23
  17:     0x563bc494dca1 - neovide::window::window_wrapper::start_loop::he9cd2f01509c2d80
                               at /home/archaic/Downloads/neovide/src/window/window_wrapper/mod.rs:235:28
  18:     0x563bc4976ec5 - neovide::window::create_window::h5147f208f1da4c15
                               at /home/archaic/Downloads/neovide/src/window/mod.rs:105:5
  19:     0x563bc4976ec5 - neovide::main::hd5135a5c130214a5
                               at /home/archaic/Downloads/neovide/src/main.rs:200:5
  20:     0x563bc493f7f3 - core::ops::function::FnOnce::call_once::hb2584da0b05d2e4d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
  21:     0x563bc493f7f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf74dbb67623022bf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:125:18
  22:     0x563bc4972561 - main
  23:     0x7f983564b565 - __libc_start_main
  24:     0x563bc477b05e - _start
  25:                0x0 - <unknown>
```

**Comment by Kethku** [comment]
"libEGL warning: DRI2: failed to authenticate" this line says to me that you are missing graphics drivers of some sort. Neovide runs on opengl so you need gpu drivers to run it.

**Comment by ruby-zen** [comment]
I already have that installed. I get this error now in `Parrot OS Home Edition`
```rust
error: could not compile `neovide`

Caused by:
  process didn't exit successfully: `rustc --crate-name neovide --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C debuginfo=2 --cfg 'feature="default"' -C metadata=c17a0f433c37d20b -C extra-filename=-c17a0f433c37d20b --out-dir /home/archaic/neovide/target/release/deps -C incremental=/home/archaic/neovide/target/release/incremental -L dependency=/home/archaic/neovide/target/release/deps --extern async_trait=/home/archaic/neovide/target/release/deps/libasync_trait-b59a5437349d382f.so --extern cfg_if=/home/archaic/neovide/target/release/deps/libcfg_if-0bc412212756a05d.rlib --extern clap=/home/archaic/neovide/target/release/deps/libclap-6685b49828a0e6d1.rlib --extern crossfire=/home/archaic/neovide/target/release/deps/libcrossfire-07fa3cb2f82d3d66.rlib --extern derive_new=/home/archaic/neovide/target/release/deps/libderive_new-2c95e35bbe6e1d7e.so --extern dirs=/home/archaic/neovide/target/release/deps/libdirs-d3615d22949eefc7.rlib --extern euclid=/home/archaic/neovide/target/release/deps/libeuclid-2bda5a603767a87a.rlib --extern flexi_logger=/home/archaic/neovide/target/release/deps/libflexi_logger-558c1fd215b5fda8.rlib --extern futures=/home/archaic/neovide/target/release/deps/libfutures-d8d4ff72a09acd29.rlib --extern gl=/home/archaic/neovide/target/release/deps/libgl-01e811b4259bd959.rlib --extern glutin=/home/archaic/neovide/target/release/deps/libglutin-367969d57e7331d8.rlib --extern image=/home/archaic/neovide/target/release/deps/libimage-afe3d807e7a90aee.rlib --extern lazy_static=/home/archaic/neovide/target/release/deps/liblazy_static-69746b95edecdf18.rlib --extern log=/home/archaic/neovide/target/release/deps/liblog-e74e20bc96977524.rlib --extern lru=/home/archaic/neovide/target/release/deps/liblru-d2e951e36167760c.rlib --extern neovide_derive=/home/archaic/neovide/target/release/deps/libneovide_derive-cc93e59a830b089f.so --extern nvim_rs=/home/archaic/neovide/target/release/deps/libnvim_rs-295a991ea27ef969.rlib --extern parking_lot=/home/archaic/neovide/target/release/deps/libparking_lot-35f5a756f7df12bb.rlib --extern pin_project=/home/archaic/neovide/target/release/deps/libpin_project-392c8ac67d4b279c.rlib --extern rand=/home/archaic/neovide/target/release/deps/librand-45ef3c762a7acf79.rlib --extern regex=/home/archaic/neovide/target/release/deps/libregex-adaf930280ef037f.rlib --extern rmpv=/home/archaic/neovide/target/release/deps/librmpv-8e0854a1e9354e41.rlib --extern rust_embed=/home/archaic/neovide/target/release/deps/librust_embed-d86f5792804ab342.rlib --extern skia_safe=/home/archaic/neovide/target/release/deps/libskia_safe-a8de592743fd7214.rlib --extern swash=/home/archaic/neovide/target/release/deps/libswash-4061d7b8e5b40440.rlib --extern tokio=/home/archaic/neovide/target/release/deps/libtokio-e524aa6ed8f1dfb0.rlib --extern unicode_segmentation=/home/archaic/neovide/target/release/deps/libunicode_segmentation-9f650cd3beeb3b42.rlib --extern which=/home/archaic/neovide/target/release/deps/libwhich-4ebb46c644c38862.rlib --extern winit=/home/archaic/neovide/target/release/deps/libwinit-12387dfd5c53deff.rlib -L /home/archaic/neovide/target/release/build/skia-bindings-1ea7a7dc34c9a9b1/out/skia` (signal: 9, SIGKILL: kill)
```

**Comment by chenhaoc** [comment]
I get this error too, anybody knows how to debug or fix?
```
error: could not compile `neovide`
Caused by:
  process didn't exit successfully:
```

**Comment by MultisampledNight** [comment]
That's a very short excerpt which doesn't show the interesting issue, could you post the whole error?

**Comment by Kethku** [comment]
Closing as this is a rust compile issue and lack of response
