### ISSUE TITLE
Neovide fails to render symbols that render fine in my terminal (same font)

### ISSUE THREAD

**Issue by Hubro** [neovide/neovide#765]
**Describe the bug**

Certain symbols and emojis that render just fine in my terminal just render as a square symbol inside Neovim.

Here is an example:

![image](https://user-images.githubusercontent.com/597206/123541660-ec2cb400-d745-11eb-9c27-1de067345102.png)

Here is the text:

```
telianoip-repo on  feature/notify-onboarding-daemon [!] via 🐍 v3.8.6 
❯ echo "Have a nice day 😊"
Have a nice day 😊

telianoip-repo on  feature/notify-onboarding-daemon [!] via 🐍 v3.8.6 
❯ 
```

Both the terminal and the editor is configured to use "Liberation Sans Mono".

**To Reproduce**
1. Open Neovide
2. Paste the above text into a blank buffer

**Expected behavior**
You should see the emojis and symbols rendered just like in the terminal.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 0.7.0
 - Neovim Version 0.4.4

**Please run `neovide --log` and paste the contents of the `.log` file here:**

It was way too long to paste (over 6000 lines):

https://gist.githubusercontent.com/Hubro/905fc1f07d13bf8727a34e3b063ecf01/raw/b78b6f4c8de5eacebfd6f6b4d08b74a06c3ad748/neovide_rCURRENT.log

**Comment by PyGamer0** [comment]
Please try the latest version (by building from main)

**Comment by shaunsingh** [comment]
I believe this is a font fallback issue with unicode symbols. I'm experiencing the same with the latest branch (macOS, FiraCode Nerd Font)

This is probably the same behavior described in https://github.com/Kethku/neovide/issues/748

**Comment by Hubro** [comment]
@PyGamer0 I installed `neovide-git` trough the AUR and it now crashes on launch:

```
 RUST_BACKTRACE=full neovide --log
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Could not load font', src/renderer/fonts/caching_shaper.rs:50:14
stack backtrace:
   0:     0x55f44058da00 - <unknown>
   1:     0x55f44035e93f - <unknown>
   2:     0x55f44058d214 - <unknown>
   3:     0x55f44058ccab - <unknown>
   4:     0x55f44058bfb5 - <unknown>
   5:     0x55f4405a81e8 - <unknown>
   6:     0x55f4405a815c - <unknown>
   7:     0x55f4405a810d - <unknown>
   8:     0x55f4402a7ec0 - <unknown>
   9:     0x55f4402a8522 - <unknown>
  10:     0x55f4402f459a - <unknown>
  11:     0x55f4404800b8 - <unknown>
  12:     0x55f4404157ca - <unknown>
  13:     0x55f440414c57 - <unknown>
  14:     0x55f440494408 - <unknown>
  15:     0x55f44048beec - <unknown>
  16:     0x55f44048b28b - <unknown>
  17:     0x55f4404c0280 - <unknown>
  18:     0x55f44048f013 - <unknown>
  19:     0x55f4404baab1 - <unknown>
  20:     0x7f50abc4bb25 - __libc_start_main
  21:     0x55f4402c2afe - <unknown>
  22:                0x0 - <unknown>
```

Log: https://gist.githubusercontent.com/Hubro/905fc1f07d13bf8727a34e3b063ecf01/raw/9add7419ee01d8e386209bf2b57a629512067600/neovide_rCURRENT.log

**Comment by Hubro** [comment]
I compiled it myself (without Arch PKGBUILD) from the main brach and omitted the `--release` flag. It still crashes, but with a more helpful stacktrace this time:

```
neovide on  main [?] is 📦 v0.7.0 via 🦀 v1.53.0 
❯ RUST_BACKTRACE=full ./target/debug/neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Could not load font', src/renderer/fonts/caching_shaper.rs:50:14
stack backtrace:
   0:     0x55f2c8fa7530 - std::backtrace_rs::backtrace::libunwind::trace::h90af754674ffafa4
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55f2c8fa7530 - std::backtrace_rs::backtrace::trace_unsynchronized::hd35318b4e6e81148
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f2c8fa7530 - std::sys_common::backtrace::_print_fmt::h7571a6f5687a20d1
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55f2c8fa7530 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he0119e0b769c2e9a
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55f2c8fcf20f - core::fmt::write::h2b69bbb8432077e1
                               at /build/rust/src/rustc-1.53.0-src/library/core/src/fmt/mod.rs:1094:17
   5:     0x55f2c8fa20a5 - std::io::Write::write_fmt::h46cf1a7fb24b0a65
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/io/mod.rs:1584:15
   6:     0x55f2c8fa976b - std::sys_common::backtrace::_print::h78ae9eccd44fa022
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55f2c8fa976b - std::sys_common::backtrace::print::h09e94b2c5bb4dae0
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55f2c8fa976b - std::panicking::default_hook::{{closure}}::hfc3b9f31beb26f15
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:208:50
   9:     0x55f2c8fa923d - std::panicking::default_hook::h24b36b429c561a5b
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:225:9
  10:     0x55f2c8fa9d8d - std::panicking::rust_panic_with_hook::hcd8fcee5516a9191
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:591:17
  11:     0x55f2c8fa9917 - std::panicking::begin_panic_handler::{{closure}}::h19af3da01a9817bd
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:497:13
  12:     0x55f2c8fa79cc - std::sys_common::backtrace::__rust_end_short_backtrace::h0a6d1565730521c9
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55f2c8fa9879 - rust_begin_unwind
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:493:5
  14:     0x55f2c7d5b3f1 - core::panicking::panic_fmt::h4cabb5e7744685f2
                               at /build/rust/src/rustc-1.53.0-src/library/core/src/panicking.rs:92:14
  15:     0x55f2c7d5b2e3 - core::option::expect_failed::h10a95671cee9fc01
                               at /build/rust/src/rustc-1.53.0-src/library/core/src/option.rs:1241:5
  16:     0x55f2c7e21e6c - core::option::Option<T>::expect::hc36b3641e17947ef
                               at /build/rust/src/rustc-1.53.0-src/library/core/src/option.rs:349:21
  17:     0x55f2c7db29e3 - neovide::renderer::fonts::caching_shaper::CachingShaper::current_font_pair::h9b8a8d838425fdf2
                               at /home/tomas/src/github/Kethku/neovide/src/renderer/fonts/caching_shaper.rs:48:9
  18:     0x55f2c7db2e1b - neovide::renderer::fonts::caching_shaper::CachingShaper::metrics::hcbc428ba52e2fa0b
                               at /home/tomas/src/github/Kethku/neovide/src/renderer/fonts/caching_shaper.rs:75:25
  19:     0x55f2c7db2f46 - neovide::renderer::fonts::caching_shaper::CachingShaper::font_base_dimensions::h4051ba3d5a5b4141
                               at /home/tomas/src/github/Kethku/neovide/src/renderer/fonts/caching_shaper.rs:87:23
  20:     0x55f2c7e0e0f3 - neovide::renderer::Renderer::update_font::h8449c88f6f793d55
                               at /home/tomas/src/github/Kethku/neovide/src/renderer/mod.rs:91:45
  21:     0x55f2c7e0fc1d - neovide::renderer::Renderer::handle_draw_command::h459da71b49b1864c
                               at /home/tomas/src/github/Kethku/neovide/src/renderer/mod.rs:244:17
  22:     0x55f2c7e10453 - neovide::renderer::Renderer::draw_frame::h4b64ccf64bad27f1
                               at /home/tomas/src/github/Kethku/neovide/src/renderer/mod.rs:272:13
  23:     0x55f2c7e7197a - neovide::window::window_wrapper::GlutinWindowWrapper::draw_frame::hb2b6313c6b369183
                               at /home/tomas/src/github/Kethku/neovide/src/window/window_wrapper/mod.rs:190:20
  24:     0x55f2c7e73106 - neovide::window::window_wrapper::start_loop::{{closure}}::h6732ffc75c3872b0
                               at /home/tomas/src/github/Kethku/neovide/src/window/window_wrapper/mod.rs:284:13
  25:     0x55f2c7ee0dc7 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return::h12f81fa1fa93171d
                               at /home/tomas/src/github/Kethku/neovide/./CARGO/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/wayland/event_loop/mod.rs:483:25
  26:     0x55f2c7ee1f43 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run::h9981feca15215ba2
                               at /home/tomas/src/github/Kethku/neovide/./CARGO/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/wayland/event_loop/mod.rs:191:9
  27:     0x55f2c7f423dc - winit::platform_impl::platform::EventLoop<T>::run::h0705ea51cc3abc50
                               at /home/tomas/src/github/Kethku/neovide/./CARGO/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:676:56
  28:     0x55f2c7e9f5ea - winit::event_loop::EventLoop<T>::run::haf42b07743e06625
                               at /home/tomas/src/github/Kethku/neovide/./CARGO/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:154:9
  29:     0x55f2c7e729af - neovide::window::window_wrapper::start_loop::h9c504348d9972d79
                               at /home/tomas/src/github/Kethku/neovide/src/window/window_wrapper/mod.rs:267:5
  30:     0x55f2c7db63d6 - neovide::window::create_window::hd316d6a0c7040c26
                               at /home/tomas/src/github/Kethku/neovide/src/window/mod.rs:105:5
  31:     0x55f2c7dddcc5 - neovide::main::ha89e83e71b90eabf
                               at /home/tomas/src/github/Kethku/neovide/src/main.rs:200:5
  32:     0x55f2c7eb65fb - core::ops::function::FnOnce::call_once::hc2bb1da6f7b9f1da
                               at /build/rust/src/rustc-1.53.0-src/library/core/src/ops/function.rs:227:5
  33:     0x55f2c7e4670e - std::sys_common::backtrace::__rust_begin_short_backtrace::h0f51d92f90a28159
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:125:18
  34:     0x55f2c7dbbe21 - std::rt::lang_start::{{closure}}::h68b8412ab6c85969
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/rt.rs:49:18
  35:     0x55f2c8faa28a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h38252fcc236f7c8b
                               at /build/rust/src/rustc-1.53.0-src/library/core/src/ops/function.rs:259:13
  36:     0x55f2c8faa28a - std::panicking::try::do_call::h1ec5110d27df1229
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:379:40
  37:     0x55f2c8faa28a - std::panicking::try::h8d5e4776be23290c
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:343:19
  38:     0x55f2c8faa28a - std::panic::catch_unwind::hf36a3ca3a68c9a49
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/panic.rs:431:14
  39:     0x55f2c8faa28a - std::rt::lang_start_internal::h82c01d0d3e63445d
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/rt.rs:34:21
  40:     0x55f2c7dbbe00 - std::rt::lang_start::h93baa337646f276c
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/rt.rs:48:5
  41:     0x55f2c7ddef4c - main
  42:     0x7fe8ae48cb25 - __libc_start_main
  43:     0x55f2c7d5bbfe - _start
  44:                0x0 - <unknown>
```

**Comment by Hubro** [comment]
If I remove my nvim config it launches successfully. Caret animations and window animations are still working, but still no smooth scrolling.

**Comment by Hubro** [comment]
I should mention I'm using Sway, a Wayland window manager, and neovide is being run as an xwayland client.

**Comment by ZeusThundr** [comment]
for smooth scrolling you have to use the  `--multiGrid` flag when launching neovide in either the .desktop file or through you whatever you use to manage keyboard shortcuts. Capitalization matters with the flag though at least for me it doesn't render certain plugins like vim clap or floaterm properly.

**Comment by Kethku** [comment]
I think the problem you are running into @Hubro is a bug where if the configured guifont isn't formatted just so for the swash/skia font finder, it crashes. I'd try fiddling with the guifont name in the meantime

**Comment by Hubro** [comment]
@Kethku My font is set like this:

```
set guifont=Liberation\ Sans\ Mono:h13
```

I'm not sure what I would tweak :thinking: Any suggestions?

**Comment by Hubro** [comment]
@Kethku Do you have a link to the font finder bug? It's currently the only thing preventing me from using Neovide.

**Comment by TimB87** [comment]
It seems like what works for me is setting multiple fonts like that: 
`set guifont=Inconsolata:h16,Twitter\ Color\ Emoji:h16,Inconsolata\ Nerd\ Font:h16`

**Comment by Kethku** [comment]
uh I think that probably won't work. We don't currently support multiple size settings.

`set guifont=Inconsolata,Twitter\ Color\ Emoji\Inconsolata\ Nerd\ Font:h16`

I think this is the correct format

**Comment by TimB87** [comment]
At least it didn't throw an error over here :) I did notice it behaving weird, however, when you actually try and set different font sizes. So this is obviously cleaner 👍

**Comment by Kethku** [comment]
@Hubro I just fixed the font finder bug. It no longer crashes, but won't warn you if the font is wrong. So it may take some trial and error to find the correct  font name

**Comment by Hubro** [comment]
@Kethku Nice! That made it a lot easier to experiment. So it seems the right font string was `Liberation\ Mono:h13` :smile: 

However, it doesn't look like Neovide renders the font quite right. Here is a comparison between Neovide with `guifont=Liberation\ Mono:h14` and nvim running in xfce4-terminal with the font set to "Liberation Mono Regular 10" (h14 was the visually most similar font size to 10 in xfce4-terminal):

![screenshot](https://user-images.githubusercontent.com/597206/123700701-16bf5f80-d861-11eb-8934-193e6ad357a4.png)

The font in Neovide seems fatter and blurrier, and isn't positioned quite correctly. It's rendered slightly too high up on the line.

Emojis also look different:

![image](https://user-images.githubusercontent.com/597206/123701235-df04e780-d861-11eb-908b-4f54ee151346.png)

Neovide appears to fall back to a different font than xfce4-terminal does, and the emojis are cropped/clipped in Neovide.

**Comment by Kethku** [comment]
These issues have been fixed in main. Please reopen if problems persist.
