### ISSUE TITLE
Manjaro snap not working

### ISSUE THREAD

**Issue by Helbis** [neovide/neovide#953]
# Describe the bug
It doesn't start up.

# To Reproduce
Just run `env RUST_BACKTRACE=full neovide`

# Desktop
## OS
> OS: Manjaro Linux x86_64
> Host: MS-7A33 2.0
> Kernel: 5.14.0-0-MANJARO
> Uptime: 7 hours, 31 mins
> Packages: 1297 (pacman), 3 (snap)
> Shell: zsh 5.8
> Resolution: 1920x1080
> WM: i3
> Theme: Adwaita [GTK3]
> Icons: Adwaita [GTK3]
> Terminal: alacritty
> Terminal Font: Source Code Pro
> CPU: AMD Ryzen 5 1500X (8) @ 3.700GHz
> GPU: NVIDIA GeForce GTX 1050 Ti
> Memory: 3894MiB / 7897MiB

## `neovide --version`
```
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Neovide 0.7.0
```

## Neovim Version
```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser
```

## Backtrace of the `env RUST_BACKTRACE=full neovide` 
```
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
No protocol specified
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:626:9
stack backtrace:
Ignored client type property: "methods"
Ignored client type property: "attributes"
   0:     0x55807fb704f0 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55807fb704f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55807fb704f0 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55807fb704f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55807f92619f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x55807fb6fd14 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x55807fb6f7ab - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55807fb6f7ab - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55807fb6f7ab - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x55807fb6eab5 - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x55807fb6eab5 - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x55807fb8a568 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:     0x55807fb8a4dc - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55807fb8a48d - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x55807f8a5930 - std::panicking::begin_panic_fmt::hd15438ecd490aab7
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
  15:     0x55807fa8ed75 - winit::platform_impl::platform::EventLoop<T>::new_any_thread::h1d017122a8041d56
                               at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:626:9
  16:     0x55807fa8ed75 - winit::platform_impl::platform::EventLoop<T>::new::h935684c61a641e83
                               at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:581:9
  17:     0x55807fa8ed75 - winit::event_loop::EventLoop<T>::with_user_event::h95ccd7d69b803283
                               at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:134:25
  18:     0x55807fa8ed75 - winit::event_loop::EventLoop<()>::new::h987334f1b5bd6d41
                               at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:120:9
  19:     0x55807fa8ed75 - neovide::window::window_wrapper::start_loop::h6a221b2ffa95330c
                               at /root/parts/neovide/build/src/window/window_wrapper/mod.rs:204:22
  20:     0x55807faa432a - neovide::window::create_window::h94e3928045b04ba1
                               at /root/parts/neovide/build/src/window/mod.rs:50:5
  21:     0x55807faa432a - neovide::main::hf6004e134216c6f2
                               at /root/parts/neovide/build/src/main.rs:198:5
  22:     0x55807fa76843 - core::ops::function::FnOnce::call_once::h32472cc38e97eb5d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
  23:     0x55807fa76843 - std::sys_common::backtrace::__rust_begin_short_backtrace::h08200308916b41c7
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:125:18
  24:     0x55807faa0441 - main
  25:     0x7fac61cb4bf7 - __libc_start_main
  26:     0x55807f8ad79a - _start
  27:                0x0 - <unknown>
```

**Additional context**
I also opened an issue #945

**Comment by PyGamer0** [comment]
I think this is because of some Wayland / X11 issues, I am not used to linux though.

**Comment by leon332157** [comment]
We just tackled this problem with a fix of the snap package. @j4qfrost did we push the changes to snapcraft yet?

**Comment by j4qfrost** [comment]
Should be, I released the fix to edge.

**Comment by leon332157** [comment]
@Helbis Can you try installing the snap from edge channel? `sudo snap install neovide --channel=edge`

**Comment by leon332157** [comment]
![image](https://user-images.githubusercontent.com/30728609/133721758-4d03b2f4-8168-456c-9989-e3394f2ba068.png)
Ok this is weird. @j4qfrost can you double check the release channel

**Comment by j4qfrost** [comment]
Yeah it should be 0.8.0 one sec.

**Comment by j4qfrost** [comment]
Forgot to hit save, thanks for the catch.

**Comment by leon332157** [comment]
OK, looks like this is still broken with the strict confinement on 0.8.0. I will look into it. It's a different error from the other issue.

**Comment by Helbis** [comment]
@leon332157 
I installed it with `sudo snap install neovide --channel=edge`.
I can't run it, maybe something is wrong with my system.

**Version**
`neovide --version`

```
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Neovide 0.8.0
```

I run the program with: `env RUST_BACKTRACE=full neovide` :

```
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
No protocol specified
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:626:9
stack backtrace:

0:     0x5622559ea060 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5622559ea060 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5622559ea060 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5622559ea060 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x56225592bf0c - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x5622559e8634 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x5622559e925b - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5622559e925b - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5622559e925b - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x5622559e8239 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x5622559e8239 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:     0x562255a02248 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  12:     0x562255a021bc - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x562255a0216d - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  14:     0x5622557e7e00 - std::panicking::begin_panic_fmt::h7ab3d84aa4ae32a2
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:457:5
  15:     0x5622558d716c - winit::platform_impl::platform::EventLoop<T>::new_any_thread::h5a04bddbacadd00b
                               at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:626:9
  16:     0x5622558d716c - winit::platform_impl::platform::EventLoop<T>::new::h78c1c155b679e2df
                               at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:581:9
  17:     0x5622558d716c - winit::event_loop::EventLoop<T>::with_user_event::hbcdc142f307f86eb
                               at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:134:25
  18:     0x5622558d716c - winit::event_loop::EventLoop<()>::new::ha8483de49395c045
                               at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:120:9
  19:     0x5622558d716c - neovide::window::window_wrapper::create_window::hc643a4a43ccebed5
                               at /root/parts/neovide/build/src/window/window_wrapper/mod.rs:244:22
  20:     0x5622558725ed - neovide::main::h6e70023db0b1cd0a
                               at /root/parts/neovide/build/src/main.rs:171:5
  21:     0x5622558347a3 - core::ops::function::FnOnce::call_once::hf6a1d5d6f2a812dd
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
  22:     0x5622558347a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h29430f71efff7f85
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:125:18
  23:     0x56225586d114 - main
  24:     0x7f0f85b520b3 - __libc_start_main
  25:     0x5622557efc4e - _start
  26:                0x0 - <unknown>
```
