### ISSUE TITLE
Neovide fails to launch upon installation with snap

### ISSUE THREAD

**Issue by MikulasVanousek** [neovide/neovide#980]
**Describe the bug**
Neovide fails to open after installation from snap store. 

**To Reproduce**
I do not think you will be able to reproduce it. 

**Expected behavior**
I expected Neovide to launch... :D

**Desktop (please complete the following information):**
 - OS: Pop!_OS 21.04 (Ubuntu 21.04 based)
 - Neovide 0.7.0
 - Neovim v0.6.0-dev

**Please run `neovide --log` and paste the contents of the `.log` file here:**
```
mkdir: cannot create directory '/run/user/0': Permission denied
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:626:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by PyGamer0** [comment]
Can you try manually building?

**Comment by zphixon** [comment]
Hello! I ran into this as well.

Ubuntu 21.04, installed via snap. The manual build following instructions in the readme worked :)

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: GlobError { path: ".", error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }', /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:150:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1037:23
   4: core::ops::function::FnMut::call_mut
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:150:5
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:280:13
   6: core::option::Option<T>::map
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:487:29
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/adapters/map.rs:101:9
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/vec/spec_from_iter_nested.rs:23:32
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/vec/spec_from_iter.rs:36:9
  10: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/vec/mod.rs:2404:9
  11: core::iter::traits::iterator::Iterator::collect
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/traits/iterator.rs:1788:9
  12: flexi_logger::writers::file_log_writer::state::rotate_output_file_to_date
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer/state.rs:587:33
  13: flexi_logger::writers::file_log_writer::state::State::initialize
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer/state.rs:169:33
  14: flexi_logger::writers::file_log_writer::state::State::write_buffer
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer/state.rs:293:13
  15: <flexi_logger::writers::file_log_writer::FileLogWriter as flexi_logger::writers::log_writer::LogWriter>::write::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:80:17
  16: std::thread::local::LocalKey<T>::try_with
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16
  17: std::thread::local::LocalKey<T>::with
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9
  18: flexi_logger::primary_writer::buffer_with
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/primary_writer.rs:329:5
  19: <flexi_logger::writers::file_log_writer::FileLogWriter as flexi_logger::writers::log_writer::LogWriter>::write
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:69:9
  20: <flexi_logger::primary_writer::MultiWriter as flexi_logger::writers::log_writer::LogWriter>::write
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/primary_writer.rs:236:13
  21: flexi_logger::primary_writer::PrimaryWriter::write
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/primary_writer.rs:63:35
  22: <flexi_logger::flexi_logger::FlexiLogger as log::Log>::log
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/flexi_logger.rs:132:9
  23: log::__private_api_log
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.14/src/lib.rs:1460:5
  24: neovide::bridge::create_nvim_command
             at /root/parts/neovide/build/src/bridge/mod.rs:131:5
  25: neovide::bridge::start_neovim_runtime::{{closure}}
             at /root/parts/neovide/build/src/bridge/mod.rs:166:61
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
  27: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
  28: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
  29: tokio::runtime::task::core::Core<T,S>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
  30: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
  31: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
  32: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:344:9
  33: std::panicking::try::do_call
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  34: std::panicking::try
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  35: std::panic::catch_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  36: tokio::runtime::task::harness::Harness<T,S>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
  37: tokio::runtime::task::raw::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
  38: tokio::runtime::task::raw::RawTask::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
  39: tokio::runtime::task::Notified<S>::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
  40: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:349:13
  41: tokio::coop::with_budget::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:127:9
  42: std::thread::local::LocalKey<T>::try_with
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16
  43: std::thread::local::LocalKey<T>::with
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9
  44: tokio::coop::with_budget
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:120:5
  45: tokio::coop::budget
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:96:5
  46: tokio::runtime::thread_pool::worker::Context::run_task
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:348:9
  47: tokio::runtime::thread_pool::worker::Context::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:320:24
  48: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:305:17
  49: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
  50: tokio::runtime::thread_pool::worker::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:302:5
  51: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:281:45
  52: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/task.rs:41:21
  53: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
  54: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
  55: tokio::runtime::task::core::Core<T,S>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
  56: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
  57: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
  58: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:344:9
  59: std::panicking::try::do_call
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  60: std::panicking::try
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  61: std::panic::catch_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  62: tokio::runtime::task::harness::Harness<T,S>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
  63: tokio::runtime::task::raw::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
  64: tokio::runtime::task::raw::RawTask::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
  65: tokio::runtime::task::Notified<S>::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
  66: tokio::runtime::blocking::pool::Inner::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:250:17
  67: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:230:21
  68: tokio::runtime::context::enter
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/context.rs:72:5
  69: tokio::runtime::handle::Handle::enter
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:76:9
  70: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:229:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:57
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1037:23
   4: <flexi_logger::writers::file_log_writer::FileLogWriter as flexi_logger::writers::log_writer::LogWriter>::write::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:39
   5: std::thread::local::LocalKey<T>::try_with
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16
   6: std::thread::local::LocalKey<T>::with
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9
   7: flexi_logger::primary_writer::buffer_with
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/primary_writer.rs:329:5
   8: <flexi_logger::writers::file_log_writer::FileLogWriter as flexi_logger::writers::log_writer::LogWriter>::write
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:69:9
   9: <flexi_logger::primary_writer::MultiWriter as flexi_logger::writers::log_writer::LogWriter>::write
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/primary_writer.rs:236:13
  10: flexi_logger::primary_writer::PrimaryWriter::write
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/primary_writer.rs:63:35
  11: <flexi_logger::flexi_logger::FlexiLogger as log::Log>::log
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/flexi_logger.rs:132:9
  12: log::__private_api_log
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.14/src/lib.rs:1460:5
  13: neovide::window::window_wrapper::start_loop
             at /root/parts/neovide/build/src/window/window_wrapper/mod.rs:202:5
  14: neovide::window::create_window
             at /root/parts/neovide/build/src/window/mod.rs:50:5
  15: neovide::main
             at /root/parts/neovide/build/src/main.rs:198:5
  16: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by MikulasVanousek** [comment]
I tried compiling from the source...
```
 Compiling rmpv v1.0.0
error[E0599]: no variant or associated item named `Unsupported` found for enum `ErrorKind` in the current scope
  --> /home/miki/.cargo/registry/src/github.com-1ecc6299db9ec823/rmpv-1.0.0/src/decode/mod.rs:41:53
   |
41 |             Error::DepthLimitExceeded => ErrorKind::Unsupported,
   |                                                     ^^^^^^^^^^^ variant or associated item not found in `ErrorKind`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rmpv`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by bnsmcx** [comment]
I had this same issue when installing from snap.  I am also running Pop_OS! 21.04.

Attempting to compile from source right now, I'll report back with my findings.

**Comment by bnsmcx** [comment]
Building from source worked fine for me on PopOS.

**Comment by bishnu-47** [comment]
installed using snap on Ubuntu 18.04, got following errors:
```
xkbcommon: ERROR: /snap/neovide/120/usr/share/X11/locale/iso8859-1/Compose:84:34: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/120/usr/share/X11/locale/iso8859-1/Compose:85:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/120/usr/share/X11/locale/iso8859-1/Compose:86:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/120/usr/share/X11/locale/iso8859-1/Compose:87:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/120/usr/share/X11/locale/iso8859-1/Compose:88:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/120/usr/share/X11/locale/iso8859-1/Compose:89:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/120/usr/share/X11/locale/iso8859-1/Compose:90:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/120/usr/share/X11/locale/iso8859-1/Compose:91:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/120/usr/share/X11/locale/iso8859-1/Compose:92:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/120/usr/share/X11/locale/iso8859-1/Compose:93:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/120/usr/share/X11/locale/iso8859-1/Compose:94:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/120/usr/share/X11/locale/iso8859-1/Compose:94:29: too many errors
xkbcommon: ERROR: /snap/neovide/120/usr/share/X11/locale/iso8859-1/Compose:94:29: failed to parse file
libGL error: MESA-LOADER: failed to retrieve device information
libEGL warning: MESA-LOADER: failed to retrieve device information

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, NoAvailablePixelFormat])', src/window/window_wrapper/mod.rs:281:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by dineshKumar777** [comment]
> I tried compiling from the source...
> 
> ```
>  Compiling rmpv v1.0.0
> error[E0599]: no variant or associated item named `Unsupported` found for enum `ErrorKind` in the current scope
>   --> /home/miki/.cargo/registry/src/github.com-1ecc6299db9ec823/rmpv-1.0.0/src/decode/mod.rs:41:53
>    |
> 41 |             Error::DepthLimitExceeded => ErrorKind::Unsupported,
>    |                                                     ^^^^^^^^^^^ variant or associated item not found in `ErrorKind`
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0599`.
> error: could not compile `rmpv`
> 
> To learn more, run the command again with --verbose.
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> ```

I believe this is fixed in recent commit. 
Can you try build from source again ???
